# Generated by Django 4.1.4 on 2022-12-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_category_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='picture',
        ),
        migrations.AddField(
            model_name='auction',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='auction',
            name='picture_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_time',
            field=models.TimeField(blank=True),
        ),
    ]
