# Generated by Django 4.1.4 on 2022-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auction_picture_auction_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='starting_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
