# Generated by Django 4.1.4 on 2022-12-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_starting_time_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_price',
            new_name='price',
        ),
    ]
