# Generated by Django 4.1.4 on 2022-12-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_duration_remove_auction_starting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
