# Generated by Django 4.1.4 on 2022-12-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bid_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='price',
            new_name='starting_price',
        ),
    ]
