# Generated by Django 4.1.4 on 2022-12-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_price_auction_starting_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='open',
            new_name='active',
        ),
        migrations.AddField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
