# Generated by Django 4.1.4 on 2022-12-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_open_auction_active_auction_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='current_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='starting_price',
        ),
    ]
